spring:
  application:
    name: nearby-place
  datasource:
    url: jdbc:h2:mem:nearby-place
    driverClassName: org.h2.Driver
    username: nearby-place
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
server:
  port: 8070

google:
  places:
    api:
      key: ${GOOGLE_MAPS_API_KEY}