name: Nearby Places Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 21
    - run: npm ci
        worworking-directory: ./nearby-places-ui
    - run: npm run build --if-present
        woworking-directory: ./nearby-places-ui
        env:
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

    - name: copy react to spring static resources
      run: |
        mkdir -p nearby-places/src/main/resources/static
        cp -a nearby-places-ui/dist/. nearby-places/src/main/resources/static/

    -name: Build Spring
      run: mvn -B package --file pom.xml
      woworking-directory: ./nearby-places
      env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

    - name: SFTP Deploy
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{secrets.USERNAME}}
        server: ${{secrets.IP}}
        ssh_private_key: ${{secrets.SSH}}
        local_path: nearby-places/target/nearby-places-0.0.1-SNAPSHOT.jar
        remote_path: home/nberimen
        password: ${{secrets.PASSWORD}}
          
